# 'main.py' generated by Pyrustic Manager
import about
from pyrustic.app import App
import os.path


app = App()
# Set window title
window_title = "{} | Built with Pyrustic".format(about.PROJECT_NAME)
app.root.title(window_title)
# Set config
config_file = os.path.join(about.ROOT_DIR, "config.ini")
app.config = config_file if os.path.exists(config_file) else None
# Set theme
app.theme = None  # feel free to use pyrustic.themes.darkmatter.DARKMATTER_THEME
# Set view
app.view = None  # please assign a View's instance to this property
# Lift off !
app.start()
