data ="""# a 'view' module generated by Pyrustic Manager
import about
import tkinter as tk
from pyrustic.abstract.viewable import Viewable
from pyrustic.widget.toast import Toast


class {}(Viewable):

    def __init__(self):
        self._body = None
        # build
        self.build()

    def _on_build(self):
        self._body = tk.Frame()
        
    def _on_display(self):
        pass

    def _on_destroy(self):
        pass

"""
