# "build_act_2.py" file generated by Pyrustic Manager
import about
import sys
import os
import os.path
from pyrustic.jasonix import Jasonix


EXIT_CODE = 0
SCRIPT_PATH = sys.argv[0]
TARGET = sys.argv[1]
CACHED_TARGET = sys.argv[2]


# Write your code here

about_json_path = os.path.join(CACHED_TARGET, "pyrustic_data", "about.json")
if os.path.exists(about_json_path):
    jasonix = Jasonix(about_json_path)
    jasonix.data["dev_mode"] = False
    jasonix.save()



# Exiting this script
sys.exit(EXIT_CODE)
